# config_dgedi.yaml

exp_name: demo
device: cuda

single_scale:
  weights_path: 'checkpoints/dGeDi_single_scale.pth'
  model_config:
    enc_channels: [32, 64, 128, 256, 512]
    enc_num_head: [2, 4, 8, 16, 32]
    dec_channels: [32, 64, 128, 256]
    dec_num_head: [4, 4, 8, 16]
    enable_flash: True ## Enable flash attention for faster inference
    normalize_features: True ## Normalize output features

multi_scale:
  weights_path: 'checkpoints/dGeDi_multi_scale.pth'
  model_config:
    enc_channels: [32, 64, 128, 256, 512]
    enc_num_head: [2, 4, 8, 16, 32]
    dec_channels: [64, 64, 128, 256]
    dec_num_head: [4, 4, 8, 16]
    enable_flash: True ## Enable flash attention for faster inference
    normalize_features: True ## Normalize output features
